services:
  
  notes-app:
    build:
      context: ./notes-app
    ports:
      - "8000:8000"
    container_name: notes-app
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
